### ISSUE TITLE
 这个要怎么用

### ISSUE THREAD

**Issue by fengfangqian** [baomingba/cordova-plugin-umeng-analytics#1]
我要统计新增用户，日活，月活，留存率等信息用你这个插件能实现吗
我看到ios下只要配置下就可以用了，这怎么实现统计呢，不需要js调用了吗?android环境下需要在每个统计的activity添加两个函数的怎么弄，我放到phonegap的MainActivty.java里报错

**Comment by landys** [comment]
这几个都支持的。这个插件主要是为了方便cordova编译集成，尽量减少`cordova build`之后的修改代码步骤。不支持自定义事件统计。基本统计功能iOS不需要js调用。Android你看看是不是没有`import com.umeng.analytics.MobclickAgent;`。另外，我刚更新了一些代码，你更新一下试试。

**Comment by fengfangqian** [comment]
@landys 我要怎么验证成功的调用了友盟的插件并数据上报给了友盟

**Comment by landys** [comment]
@fengfangqian 去友盟统计后台看有没有数据，可能会有一些延迟。

**Comment by fengfangqian** [comment]
我把那两个函数加在了CordovaApp.java的类CordovaApp里面,请问需要在什么地方显示调用么?

**Comment by fengfangqian** [comment]
@landys 友盟后台也没数据,程序也没报错,这要咋整

**Comment by landys** [comment]
@fengfangqian 这两函数主要是用来统计用户停留在app上的时间的，所以你要统计的Activity里都要加。比如继承了CordovaActivity的那个类里。

**Comment by landys** [comment]
@fengfangqian 至于没有数据的问题，以ios为例，确定`config.xml`中`<preference name="UmengIOSAppId" value="123456789012345678901234" />`确定这里的id正确配置了你自己的umeng id，然后再在xcode debug确定`AppDelegate+UmengAnalytics.h`中的方法`initUmengAnalyticsApp:`被正确调用了。
