### ISSUE TITLE
为什么会自动在manifest文件里会自动生成空的umeng_key

### ISSUE THREAD

**Issue by fengfangqian** [baomingba/cordova-plugin-umeng-analytics#2]
@landys 我安装插件后在manifest文件里会自动有下面两行代码，我替换掉appkey以后
<meta-data android:name="UMENG_APPKEY" android:value="552fc945fd98c58ce9000a24" />
 <meta-data android:name="UMENG_CHANNEL" android:value="Test" />
  我再cordova run android后又会自动添加如下一行配置，删掉重跑又会自动添加进来，改掉里面的值也不行，请问这是什么原因导致的
        <meta-data android:name="UMENG_APPKEY" android:value="YOUR_UMENG_APP_KEY" />

**Comment by fengfangqian** [comment]
@landys ios上是ok的，友盟可以接收到数据，现在就Android有问题，希望得到你的协助

**Comment by fengfangqian** [comment]
@landys android多次写umeng_appkey的问题已经解决，因为plugins/android.json里的
{
                            "xml": "<meta-data android:name=\"UMENG_APPKEY\" android:value=\"YOUR_UMENG_APP_KEY\" />",
                            "count": 1
                        },
导致每次修改manifest文件后，每次编译都会用初始值覆盖manifest里的值，所以需要插件在添加的时候支持--variable UMENG_APPKEY=XXXX的支持
我通过直接修改android.json文件里的值搞定了，希望你能改进这个插件，3Q

**Comment by landys** [comment]
@fengfangqian 嗯，你的建议不错，刚修改了下，已经支持`--variable UMENG_IOS_ID="123456789" --variable UMENG_ANDROID_ID="987654321"`。
